package ru.tinkoff.fintech.lesson4

fun main() {
    println("Create queue and insert elements")
    val queue = Queue<Int>()
    println("Add an element: ${queue.offer(2)}")
    println("Get an element: ${queue.peek()}")
    println("Remove an element: ${queue.remove()}")
    println("Add an element: ${queue.offer(2)}")
    println("Add an element: ${queue.offer(4)}")
    println("Add an element: ${queue.offer(1)}")
    println("Poll an element: ${queue.poll()}")
    println("Poll an element: ${queue.poll()}")
    println("Poll an element: ${queue.poll()}")
    println("Poll an element: ${queue.poll()}")

    println()
    println("Create stack and insert elements")
    val stack = Stack<Int>()
    println("Add an element: ${stack.push(2)}")
    println("Add an element: ${stack.push(1)}")
    println("Add an element: ${stack.push(3)}")
    println("Add an element: ${stack.push(4)}")
    println("Add an element: ${stack.push(5)}")
    println("Add an element: ${stack.push(6)}")
    println("Add an element: ${stack.push(7)}")
    println("Pop an element: ${stack.pop()}")
    println("Pop an element: ${stack.pop()}")
    println("Pop an element: ${stack.pop()}")
    println("Pop an element: ${stack.pop()}")
    println("Pop an element: ${stack.pop()}")
    println("Get an element: ${stack.peek()}")
    println("Pop an element: ${stack.pop()}")
    println("Get an element: ${stack.peek()}")
    println("Pop an element: ${stack.pop()}")
    println("Get an element: ${stack.peek()}")
    println("Pop an element: ${stack.pop()}")
}