INSERT INTO STUDENT_INFO (logging) VALUES('Kimineuc');
INSERT INTO STUDENT_INFO (logging) VALUES('Woric');
INSERT INTO STUDENT_INFO (logging) VALUES('Gerdes');
INSERT INTO STUDENT_INFO (logging) VALUES('Nein');