spring:
  application.name: events
  profiles.active: dev
  datasource:
    url: jdbc:h2:mem:studentdb
    username: admin
    password: admin
    driverClassName: org.h2.Driver
  jpa:
    show-sql: true
    open-in-view: false
  liquibase:
    change-log: changelog/db.changelog-master.xml
    enabled: true
server.port: 9000

events.information: http://localhost:9001
jms.broker.url: tcp://localhost:61616
jms.queue.name: IN_QUEUE

activemq.broker-url: vm://embedded?broker.persistent=false,useShutdownHook=falsein-memory
